### ISSUE TITLE
Add proxy support

### ISSUE THREAD

**Issue by Maijin** [PoshSec/PoshSecFramework#13]
Could be nice to be able to download script and update help when using a proxy http://vhusker.com/?p=93 for example

**Comment by Good-man** [comment]
Is there any reason not to use the system proxy by default?  We could add a PSF override under settings, but this should satisfy the most common use case.

![image](https://user-images.githubusercontent.com/4473709/40950162-9d9ad196-683f-11e8-99d5-da6af6cf9a3d.png)

**Comment by Good-man** [comment]
I have confirmed that this works.  I will leave the issue open until a PSF system proxy override is implemented.

**Comment by mwjcomputing** [comment]
@Good-man I agree that using the system value would satisfy the most common use case. But I agree we need a way to override.

**Comment by Good-man** [comment]
![image](https://user-images.githubusercontent.com/4473709/41165734-657e6136-6b0c-11e8-9dac-512f7aa38dd8.png)

**Comment by mwjcomputing** [comment]
Cool. I will test on a network with a proxy tomorrow and let you know, but all features still seem to be working with this support on a non proxy'd network.
