### ISSUE TITLE
FTS displays wrong note

### ISSUE THREAD

**Issue by mwjcomputing** [PoshSec/PoshSecFramework#22]
When running FTS and the initial download fails, the description says it executed successfully.

![image](https://cloud.githubusercontent.com/assets/1275370/5107725/1bfbef6c-6fd2-11e4-923d-5b598e4a4684.png)

**Comment by Good-man** [comment]
See fix at commit 9e60851eea3c3be2e6b7ddd82956cb7fcd192156
