### ISSUE TITLE
Add individual hosts

### ISSUE THREAD

**Issue by mwjcomputing** [PoshSec/PoshSecFramework#23]
I want to be able to add specific hosts without scanning.

**Comment by Good-man** [comment]
@mwjcomputing and @addisg, could you provide more detail about how you'd like this to work?  Perhaps provide a screenshot.

**Comment by mwjcomputing** [comment]
Really how I would like this to work is Let me add a new test network and then set individual hosts. By hostname or by IP address into the collection. Then allow me to just scan those hosts in the collection.

I think that makes sense.

![image](https://user-images.githubusercontent.com/1275370/41203370-d31e6d38-6ca3-11e8-8825-f092a5001272.png)

**Comment by Good-man** [comment]
@mwjcomputing when PSF starts up, it loads the Systems that are saved in the user.config.  I didn't realize that it was doing this when I saved other settings.  I could see saving a list of systems to a file, similar to the Export feature and optionally reloading them at startup, but I'm not sure that these systems should be a default setting.

**Comment by Good-man** [comment]
A related question that I have is should the network and systems be persisted somewhere?  Should PSF save/restore the networks and systems automatically without asking, or should the user have to click save?  If save, should this be stored in the central user.config or should the user be able to specify a file (Save As).   Based on issue #15 (Multiple configs when running the FrameWork), I'm guessing the later.

**Comment by Good-man** [comment]
@mwjcomputing take a look at this and let me know if it provides the **basic** functionality that you're looking for.
