### ISSUE TITLE
Search up to one to two levels down for psm1 files

### ISSUE THREAD

**Issue by mwjcomputing** [PoshSec/PoshSecFramework#25]
Take a look at [https://github.com/mwjcomputing/PoshSec/tree/Development](https://github.com/mwjcomputing/PoshSec/tree/Development). I moved the module files one level deep to keep the Pester tests out of the distribution.

Can we make this work so it can search the second level down in a module that is hosted on Github? Other PowerShell module writers are doing their module this way. Ping me if you want to chat.

**Comment by Good-man** [comment]
@mwjcomputing, do you want it to search the root and every folder at the root directory, **or** just the 2nd level and not the root?

**Comment by Good-man** [comment]
@mwjcomputing this is what I see when I try to add the modules at the URL above.

![image](https://user-images.githubusercontent.com/4473709/42090725-85e3f00c-7b70-11e8-9cf9-ee91533a027a.png)

**Comment by Good-man** [comment]
Closing the issue until further information can be provided.
