### ISSUE TITLE
Module Dropdown Doesn't Display Modules

### ISSUE THREAD

**Issue by mwjcomputing** [PoshSec/PoshSecFramework#27]
The module display always says All. It should have the name of the modules that PoshSec Framework found.

**Comment by Good-man** [comment]
Are you referring to this drop down?  The list should contain all modules shown below?   What should happen when a module is selected?

![image](https://user-images.githubusercontent.com/4473709/40852806-c19f38d2-6599-11e8-81fd-261b2b66d551.png)

**Comment by mwjcomputing** [comment]
Yep. That drop down.

The list of commands below should be limited to the contents of that module.

If you select Bitlocker, only the bitlocker commands show up.

**Comment by Good-man** [comment]
Hey Matt, check out pull request #31 and let me know if it does what you want.
