### ISSUE TITLE
Rate Limit Feature not functioning.

### ISSUE THREAD

**Issue by mwjcomputing** [PoshSec/PoshSecFramework#28]
When you go to add a new module (Tools->Options->Modules) the current rate limit doesn't show up even if I put in a Github Personal Access Token.

![image](https://user-images.githubusercontent.com/1275370/40853399-f84c81da-659b-11e8-9137-dd59a77ed2a6.png)

**Comment by Good-man** [comment]
Rate limit feature fixed in PR #33.
