### ISSUE TITLE
Can't Update Repository

### ISSUE THREAD

**Issue by mwjcomputing** [PoshSec/PoshSecFramework#29]
When you go to Tools->Options->Modules and click on a module. The Update button doesn't work (Circled in red below). 

This feature should pull down the latest copy of the module. In this example, PoshSec.

![image](https://user-images.githubusercontent.com/1275370/40853611-bece748a-659c-11e8-9223-34f5a780c92a.png)

**Comment by mwjcomputing** [comment]
I think this is tied to issue #25

**Comment by Good-man** [comment]
This is fixed by pull request #32, set SecurityProtocol to TLS 1.1 or 1.2
