### ISSUE TITLE
Can't download new module

### ISSUE THREAD

**Issue by mwjcomputing** [PoshSec/PoshSecFramework#30]
When you go to download a new module (Tools->Options->Modules) and add a module to clone, it doesn't allow you to add as it says it is invalid.

Steps:
1. Add Module
![image](https://user-images.githubusercontent.com/1275370/40853836-6d1a631e-659d-11e8-8ede-5422e6a86bd2.png)

2. Add PowerSploit Repo 
![image](https://user-images.githubusercontent.com/1275370/40853919-a459c734-659d-11e8-9dd8-a129d1d76acb.png)

3. Click Tab
4. Resulting Window
![image](https://user-images.githubusercontent.com/1275370/40853952-c1050a56-659d-11e8-9d53-8f375d5eeb22.png)

What should happen:
1. It allows you to select the branch
2. It allows you to click ok.

**Comment by mwjcomputing** [comment]
I think this is tied to issue #25 .

**Comment by Good-man** [comment]
Yes, I agree.  I think it's a related issue.  In general, web requests to GitHub are failing.

![image](https://user-images.githubusercontent.com/4473709/40878837-099d319a-6665-11e8-8ce6-4be0603373c5.png)

**Comment by Good-man** [comment]
Looks like it might be related to this:  https://developer.github.com/changes/2018-02-01-weak-crypto-removal-notice/

On Feb 8th, GitHub disabled TLS 1 & 1.1 and a couple of weak diffie hellman ciphers.  

I'll see if I can find a solution. Stay tuned.

**Comment by Good-man** [comment]
OK, found it.  Just need to set .NET to use TLS 1.1 or 1.2.  

![image](https://user-images.githubusercontent.com/4473709/40878967-d915fc6c-6666-11e8-9416-30f362fdf2ca.png)

Now it works and it should fix any related problems, too.

![image](https://user-images.githubusercontent.com/4473709/40878971-e8bb651c-6666-11e8-9902-c689dcdac1dd.png)

**Comment by Good-man** [comment]
See pull request #32, set SecurityProtocol to TLS 1.1 or 1.2.
